"""init

Revision ID: 35a3e95d72db
Revises:
Create Date: 2025-10-31 14:59:04.177356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35a3e95d72db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("telegram_id", name=op.f("users_pkey")),
    )
    op.create_table(
        "months",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_id"], ["users.telegram_id"], name=op.f("months_telegram_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("months_pkey")),
    )
    op.create_index(op.f("months_id_idx"), "months", ["id"], unique=False)
    op.create_table(
        "shifts",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("month_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["month_id"], ["months.id"], name=op.f("shifts_month_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"], ["users.telegram_id"], name=op.f("shifts_telegram_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("shifts_pkey")),
    )
    op.create_index(op.f("shifts_id_idx"), "shifts", ["id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["shifts.id"], name=op.f("orders_shift_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
    )
    op.create_index(op.f("orders_id_idx"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("orders_id_idx"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("shifts_id_idx"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_index(op.f("months_id_idx"), table_name="months")
    op.drop_table("months")
    op.drop_table("users")
    # ### end Alembic commands ###
